[package]
name = "dan-fritchman-rust-lang-book-crates"
version = "0.1.0"
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
description = "Publishing tutorial from The Rust Programming Language, Chapter 14"
license = "MIT"

[dependencies]
